### ISSUE TITLE
Update and validate `gold:Gs0114675` / `nmdc:sty-11-8fb6t785` Deep subsurface shale (metagenomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#102]
Omics Type(s): metagenomes

Steps:
Note - All records are failed by `extract-records` as OmicsProcessing missing Data Object.

Re-ID process (nmdc_automation) **re_id_tool.py** commands:
- [x] `update-study`

Validation process (nmdc_schema):
- [ ] Extract Study data as YAML with nmdc_database_tools.py `extract-study`
- [ ] Validate to current schema with `linkml-validate`

Data portal validation:
- [ ] 23 samples, 23 metagenomes

**Comment by aclum** [comment]
@mbthornton-lbl This deleted all the omics records b/c the outputs don't exist. I propose I unset has_output for the omics records and we update the protocol for this study to ONLY run update-study.

**Comment by aclum** [comment]
I have set has_output for the omics processing set records to empty lists with queries:run on dev, napa and prod. Unset commands do not appear to work currently. This removes the referential integrity issues.
