### ISSUE TITLE
Update and validate `gold:Gs0135149` / `nmdc:sty-11-dcqce727` Crested Butte (metagenomes, metatranscriptomes, NOM)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#105]
Omics Type(s): metagenomes, metatranscriptomes, NOM

Steps:

MetaG / MetaT:
Re-ID process (nmdc_automation) **re_id_tool.py** commands:
- [x] `update-study`
- [x] `extract-records`
- [x] `process-records`  (mint new IDs)
- [x] `process-records --update-links` (make updates on filesystem)
- [x] `ingest-records`
- [x] `delete-old-records`

NOM:
handled by update-study

Validation process (nmdc_schema):
- [x] Extract Study data as YAML with nmdc_database_tools.py `extract-study`
- [x] Validate to current schema with `linkml-validate`

Data portal validation:
- [x] 53 samples, 48 metagenomes, 45 metatranscriptomes, 652 NOM

**Comment by aclum** [comment]
We need to rerun update-study, there are still 5 biosamples that have igsn as the main id. We fixed a bug in the code yesterday so it should be resolved by re-running.

**Comment by aclum** [comment]
#125 blocking issue, biosample_set does not validate with linkml b/c of igsn records

**Comment by mbthornton-lbl** [comment]
Extracted and validated with `linkml-validate`: No issues found

**Comment by aclum** [comment]
There are 5 legacy assembly records for this study that didn't get re-ided


db.getCollection(
--
'metagenome_assembly_set'
).aggregate(
[
{
$match: {
id: {
$not: { $regex: RegExp('nmdc:wf') }
}
}
},
{
$lookup: {
from: 'omics_processing_set',
localField: 'was_informed_by',
foreignField:
'gold_sequencing_project_identifiers',
as: 'omics_processing_set'
}
},
{
$group: {
_id: '$omics_processing_set.part_of',
count: { $sum: 1 }
}
}
],
{ maxTimeMS: 60000, allowDiskUse: true }
);
