### ISSUE TITLE
update MAGs version for workflow automation

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#107]
This version has the reference paths fixed and incorporates eukcc. This allows allows for a specification of a mapping file. Please update to this version so we can resume binning for workflows that we've run end to end. There is a separate ticket to deal with processing when assemblies are ingest from JGI. 

Please run a few datasets through and we can check the results.
https://github.com/microbiomedata/metaMAGs/releases/tag/v1.3.3

cc @chienchi @kaijli

**Comment by aclum** [comment]
backlog until we get fixes from neha to deal with nmdc headers.

**Comment by aclum** [comment]
@scanon  to make the binning tar file work properly we need to update on the automation side to use the mapping file.

The output to annotation generates a file of data_object_type 'Contig Mapping File', that needs to be passed in to the wdl in the input.json as 'map_file', see line 20 of https://github.com/microbiomedata/metaMAGs/blob/bf6e44f43e519b1f2128c35a00d53ada8bc25551/mbin_nmdc.wdl#L20C15-L20C23

**Comment by aclum** [comment]
Ie for annotation task nmdc:wfmgan-11-h2bjdv05.1, file nmdc_wfmgan-11-h2bjdv05.1_contig_names_mapping.tsv needs to be passed as an input to the MAG task.

**Comment by aclum** [comment]
Alicia and Shane met this afternoon, Shane will test the branch in the linked PR. Code changes may be needed to make it explicit that the assembly file is the output of assembly, not annotation.

**Comment by ssarrafan** [comment]
Check with Shane Friday 7/26/24. If not done, move to next sprint.

**Comment by ssarrafan** [comment]
Moving to next sprint.
