### ISSUE TITLE
Update and validate `gold:Gs0110138` / `nmdc:sty-11-33fbta56` SPRUCE (metagenomes, NOM, proteomics, metatranscritpomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#109]
Omics Type(s): metagenomes, metatranscriptomes, proteomics, NOM

Steps:

- [x] Add missing omics and biosample records - must be done before running **update-study**
[20240129.spruce_mt_fixes.json](https://github.com/microbiomedata/nmdc_automation/files/15195393/20240129.spruce_mt_fixes.json)

MetaG / metaT
Re-ID process (nmdc_automation) **re_id_tool.py** commands:
- [x] `update-study` **requires using identifiers mapping file from repo**
- [x] `extract-records`
- [x] `process-records`  (mint new IDs)
- [x] `process-records --update-links` (make updates on filesystem)
- [x] `ingest-records`
- [x] `delete-old-records`

NOM:
handled by update-study

Proteomics:
- [x] add missing data_object_set records (proteomics raw data) 
[nmdc.data_objects_set.spruce.metap.2024-04-30-01.json](https://github.com/microbiomedata/nmdc_automation/files/15195358/nmdc.data_objects_set.spruce.metap.2024-04-30-01.json)
- [x] changesheets to update omics_processing_set has_output records -**depends on update-study** 
[  changesheet tsv file](https://drive.google.com/file/d/167M6OKTUBblB4eGvB0cxwQaHdfYbHTz_/view?usp=sharing)
- [x] metap_records_delete.py if not already run for gold:Gs0114663 - can be run before or after two steps above.

Validation process (nmdc_schema):
- [x] Extract Study data as YAML with nmdc_database_tools.py `extract-study`
- [x] Validate to current schema with `linkml-validate`

Data portal validation:
- [ ] 124 samples, 107 metagenomes, 16 metatranscriptomes, 50 NOM, 19 proteomics. **Note this different than what is on prod now.**

**Comment by aclum** [comment]
https://github.com/microbiomedata/issues/issues/527 needs to be added as a step before MetaG / metaT

**Comment by aclum** [comment]
We'd talked about using the same omics records for the proteomics data, these have new identifiers so we need to figure out what to do with the data_object_set records or roll this back, apply https://github.com/microbiomedata/nmdc_automation/issues/87 and the redo the iding.

**Comment by mbthornton-lbl** [comment]
@aclum 
Loaded the missing biosample and omics records to Napa db and ran the improved `update-study` command. 
This query:
```
db.getCollection("omics_processing_set").aggregate([
    {
        $match: {
            "id": { "$not": /^nmdc:omprc-/ }
        }
    },
    {
        $group: {
            _id: "$omics_type.has_raw_value",
            count: { $sum: 1 }
        }
    }
])
``` 
finds 
```
{
    "_id" : "Organic Matter Characterization",
    "count" : 99.0
}
{
    "_id" : "Lipidomics",
    "count" : 2.0
}
```

**Comment by aclum** [comment]
@mbthornton-lbl  that is the expected result given that you still need to re-run update-study on gold:Gs0135149 (#105). If you group by $part_of instead of omics_type.has_raw_value it shows that all remaining noncompliant records are for Crested Butte (gold:Gs0135149)

db.getCollection(
--
'omics_processing_set'
).aggregate(
[
{
$match: {
id: { $not: RegExp('^nmdc:omprc-') }
}
},
{
$group: {
_id: '$part_of',
count: { $sum: 1 }
}
}
],
{ maxTimeMS: 60000, allowDiskUse: true }
);

returns

{
  "_id": [
    "gold:Gs0135149"
  ],
  "count": 101
}

**Comment by aclum** [comment]
@mbthornton-lbl the biosample_set records got added but the omics_processing_set records did not so this is missing 16 metatranscriptomes.
