### ISSUE TITLE
add lipidomics delete function to re-id tool

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#119]
We are missing a function to delete lipidomics records and their downstream data objects

1) find lipidomics records
db.getCollection('omics_processing_set').find({
--
'omics_type.has_raw_value': 'Lipidomics'
});
2) get data object ids from has_output
3) delete omics_processing_set records by omics_processing_set.id and data_object_set record by omics_processing_set.has_output 

cc @corilo

**Comment by mbthornton-lbl** [comment]
Duplicate - implemented in the linked PR
