### ISSUE TITLE
Add support needed for ID mapping

### ISSUE THREAD

**Issue by scanon** [microbiomedata/nmdc_automation#132]
We have cases where we want to trigger ID mapping in the annotation workflow and then pass this through to later stages.  This needs a few things.

- [x] Ability to include the activity ID from a predecessor activity (e.g. the assembly activity passed through as input for annotation)
- [x] Support for optional inputs
- [x] Support for optional outputs

**Comment by aclum** [comment]
closing because there is a linked merged PR.
