### ISSUE TITLE
update nmdc_automation/configs/workflows.yaml for berkeley schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#150]
Update values to berkeley schema class names for:
Workflows.Type
Workflows.Activity.name
Workflows.Activity.type

**Comment by mslarae13** [comment]
@aclum the linked PR is waiting for Shane and Micheal to review, correct?

**Comment by aclum** [comment]
correct

**Comment by ssarrafan** [comment]
I pinged Shane and Michael to review on Slack but it doesn't look like it was reviewed yet.  @scanon @mbthornton-lbl

**Comment by mslarae13** [comment]
@aclum is this roll out MVP?
Or post roll out eligible?

**Comment by ssarrafan** [comment]
@scanon @mbthornton-lbl pinging you again to review please
@aclum since you're out today I'll move to the next sprint

**Comment by aclum** [comment]
This is part of the MVP

**Comment by aclum** [comment]
PR was merged into the berkeley branch ([219-refactor-workflow_automation-to-use-berkley-metadata-models](https://github.com/microbiomedata/nmdc_automation/tree/219-refactor-workflow_automation-to-use-berkley-metadata-models)) today.
