### ISSUE TITLE
Update nmdc_automation/configs/import.yaml for Berkeley schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#151]
Update the following to Berkeley class names
Workflows.Type
Workflows.Activity.name
Workflows.Activity.type
Data Objects.Unique.input_to
Data Objects.Unique.output_of

**Comment by aclum** [comment]
duplicate

**Comment by aclum** [comment]
Reopen, this is the import yaml, not the workflow yaml.

**Comment by ssarrafan** [comment]
Pinged Shane and Michael on PR and on Slack to review.  Not reviewed yet.

**Comment by ssarrafan** [comment]
@scanon @mbthornton-lbl can this be reviewed please?
@aclum since you're out I'll move this to the next sprint but hasn't been updated in 2 weeks

**Comment by aclum** [comment]
PR was merged into the berkeley branch ([219-refactor-workflow_automation-to-use-berkley-metadata-models](https://github.com/microbiomedata/nmdc_automation/tree/219-refactor-workflow_automation-to-use-berkley-metadata-models)) today.
