### ISSUE TITLE
update nmdc_automation/workflow_automation/activities.py for berkeley schema 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#153]
- [x] replace omics_processing_set references with data_generation_set
- [x] replace references to nmdc:OmicsProcessing to nmdc:NucleotideSequencing

**Comment by mslarae13** [comment]
@aclum who should be assigned to this?

**Comment by aclum** [comment]
Made this a while ago, feel free to close if this is a duplicate of tickets you made when doing your planning.
