### ISSUE TITLE
Update gold:Gs0110138 / nmdc:sty-11-33fbta56 SPRUCE (metagenomes, NOM, proteomics, metatranscritpomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#167]
Omics Type(s): metagenomes, metatranscriptomes, proteomics, NOM

Steps:
Missing Data
- [x] load biosample_set.json
- [x] load omics_processing_set.json

Note: omics_processing was not loaded during testing, so we will need to re-run `extract-records` and `process-records` below
QC data addition
- [x] 124 biosample_set records are returned with this find query {"part_of": "nmdc:sty-11-33fbta56"}
- [x] 16 omics_processing_set records returned with this find query {"omics_type.has_raw_value":"Metatranscriptome", "part_of": "nmdc:sty-11-33fbta56"}

Metagenomics - Note filesystem updates for SPRUCE are here: #175 

- [x] `update-study` with updated_identifiers.tsv
~- [ ] `extract-records`~
~- [ ] `process-records` no filesystem with updated_identifiers.tsv~
- [x] `ingest-records` nmdc:sty-11-33fbta56_re_ided_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-33fbta56_associated_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-33fbta56_failed_record_dump.json
- [x] re-add omics_processing_set.json

Proteomics:
- [x] add missing data_object_set records (proteomics raw data) 
[nmdc.data_objects_set.spruce.metap.2024-04-30-01.json](https://github.com/microbiomedata/nmdc_automation/files/15195358/nmdc.data_objects_set.spruce.metap.2024-04-30-01.json)
- [x] changesheets to update omics_processing_set has_output records -**depends on update-study** 
[  changesheet tsv file](https://drive.google.com/file/d/167M6OKTUBblB4eGvB0cxwQaHdfYbHTz_/view?usp=sharing)
- [x] metap_records_delete.py if not already run for gold:Gs0114663 - can be run before or after two steps above.

**Comment by ssarrafan** [comment]
Sprint over, removing from sprint.

**Comment by mbthornton-lbl** [comment]
Data Prerequisites for SPRUCE

[nmdc:sty-11-33fbta56_biosample_set.json](https://github.com/microbiomedata/nmdc_automation/files/15407648/nmdc.sty-11-33fbta56_biosample_set.json)
[nmdc:sty-11-33fbta56_omics_processing_set.json](https://github.com/microbiomedata/nmdc_automation/files/15407652/nmdc.sty-11-33fbta56_omics_processing_set.json)
[nmdc:sty-11-33fbta56_updated_record_identifiers.txt](https://github.com/microbiomedata/nmdc_automation/files/15407679/nmdc.sty-11-33fbta56_updated_record_identifiers.txt)

@aclum These are the data docs from the automation repository `napa_reid_data_and_logs` branch, the same as were used in the first, failed reid attempt.  I am assuming we will be using these for a second run - could you please have a look at these and confirm?

**Comment by mbthornton-lbl** [comment]
[nmdc:sty-11-33fbta56_prot_data_objects.json](https://github.com/microbiomedata/nmdc_automation/files/15407727/nmdc.sty-11-33fbta56_prot_data_objects.json)

**Comment by aclum** [comment]
Okay to close :)
