### ISSUE TITLE
Update gold:Gs0103573 / nmdc:sty-11-1t150432 Populus root microbiome (metagenomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#168]
Study: gold:Gs0103573 / nmdc:sty-11-1t150432
Title: Populus root microbiome
Omics Type(s): metagenomes

Steps:
- [x] `update-study` with updated_identifiers.tsv
- [x] `ingest-records` nmdc:sty-11-1t150432_re_ided_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-1t150432_associated_record_dump.json

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.
