### ISSUE TITLE
Update gold:Gs0154244 / nmdc:sty-11-547rwq94 EMP (metagenomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#169]
Steps:
- [x] `update-study` nmdc:sty-11-547rwq94_updated_record_identifiers.tsv
- [x] `ingest-records` nmdc:sty-11-547rwq94_re_ided_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-547rwq94_associated_record_dump.json
- [x] `delete-old-records --failed-records` nmdc:sty-11-547rwq94_failed_record_dump.json

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.
