### ISSUE TITLE
Update gold:Gs0114663 / nmdc:sty-11-aygzgv51 Riverbed sediment (metabolomics, metagenomes, NOM, proteomics)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#170]
Steps:

- [x] `update-study` nmdc:sty-11-aygzgv51_updated_record_identifiers.tsv
- [x] `extract-records`
- [x] `process-records` no filesystem changes
- [x] #178 
- [x] `ingest-records` nmdc:sty-11-aygzgv51_re_ided_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-aygzgv51_associated_record_dump.json
- [x] `delete-old-records --failed-records` nmdc:sty-11-aygzgv51_failed_record_dump.json

proteomics:
- [x] add missing data_object_set records via json:submit(proteomics raw data)
[nmdc.data_objects_set.stegen.metap.2024-04-30-03.json](https://github.com/microbiomedata/nmdc_automation/files/15169764/nmdc.data_objects_set.stegen.metap.2024-04-30-03.json)
- [x] changesheets:submit to update omics_processing_set has_output records, using this [tsv file](https://drive.google.com/file/d/1z31xtHPChhbeNfm9WcZyhzKuiwJ4_yrO/view?usp=sharing)
- [x] metap_records_delete.py if not already run for nmdc:sty-11-33fbta56 - can be run before or after two steps above.

**Comment by ssarrafan** [comment]
Sprint over, removing from sprint.

**Comment by aclum** [comment]
Okay to close
