### ISSUE TITLE
Update gold:Gs0135149 / nmdc:sty-11-dcqce727 Crested Butte (metagenomes, metatranscriptomes, NOM)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#171]
Steps:

- [x] `update-study` nmdc:sty-11-dcqce727_updated_record_identifiers.tsv
- [x] `ingest-records` nmdc:sty-11-dcqce727_re_ided_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-dcqce727_associated_record_dump.json
- [x] `delete-old-records --failed-records` nmdc:sty-11-dcqce727_failed_record_dump.json

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.
