### ISSUE TITLE
Re-ID Studies for Prod

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#172]
In the cloned-from-prod Napa environment

**Update Studies:**
- [x] #166 
- [x] #168
- [x] #169
- [x] #171
- [x] #173 
- [x] #174

After all studies are updates, Run `data_qc` queries against the entire DB:
- [x] biosample_part_of_study.js
- [x] data_object_was_generated_by_activity_or_omics_processing.js
- [x] extraction_has_input_biosample_or_processed_sample.js
~[ ] functional_annotation_agg_metagenome_metatranscriptome_annotation_id.js~
- [x] metabolomics_analysis_acrtivity_has_calibration_data_object.js
- [x] nom_analysis_activity_has_calibration_data_object.js
- [x] omics_processing_has_input_biosample_or_processed_sample.js (24 failing SPRUCE records)
- [x] omics_processing_has_output_data_objects.js. (19 failing SPRUCE records)
- [x] omics_processing_part_of_study.js
- [x] orphan_data_objects.js
- [x] pooling_has_input_biosample_or_processed_sample.js
- [x] workflow_execution_has_input_data_objects.js
- [x] workflow_execution_has_output_data_objects.js
- [x] workflow_execution_was_informed_by_omics_processing.js

Note:  DataObject queries were filtered for re-IDed data objects

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.
