### ISSUE TITLE
Update gold:Gs0128850 / nmdc:sty-11-076c9980 Wet Tropical Soils (metagenomes)

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#174]
Steps:

- [x] `update-study` nmdc:sty-11-076c9980_updated_record_identifiers.tsv
- [x] `ingest-records` nmdc:sty-11-076c9980_re_ided_record_dump.json
- [x] `delete-old-records` nmdc:sty-11-076c9980_associated_record_dump.json

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.
