### ISSUE TITLE
Delete `generate_functional_agg.py` if it is redundant

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc_automation#180]
I was browsing the `nmdc_automation/workflow_automation` directory in this repository while learning about the scheduler, and I noticed the directory contained a file named `generate_functional_agg.py`.

- [`nmdc_automation/workflow_automation/generate_functional_agg.py`](https://github.com/microbiomedata/nmdc_automation/blob/main/nmdc_automation/workflow_automation/generate_functional_agg.py)

The "aggregation-related" files that were recently extracted from the `infra-admin` repository into their own repository (`nmdc-aggregator`) happen to include a file having that same name.

- [`generate_functional_agg.py`](https://github.com/microbiomedata/nmdc-aggregator/blob/main/generate_functional_agg.py)

I am wondering whether these two files are redundant and whether the one in this repository can be safely deleted. I noticed it does not import any other files in this repository, and no other files in this repository import _it_.

**Comment by aclum** [comment]
Yes, this is okay to delete.
