### ISSUE TITLE
mg_annotation update v1.1.0

### ISSUE THREAD

**Issue by kaijli** [microbiomedata/nmdc_automation#191]
Added support to use fasta_sanity.py to generate mapping file, bridging naming scheme between JGI and NMDC data. 
https://github.com/microbiomedata/mg_annotation/pull/28
Automation needs update to run through NEON datasets

- [ ] update version used in config file to v1.1.0
- [ ] make a data object record to store the *_contig_names_mapping.tsv file with a data_object_type of 'Contig Mapping File' as an output file generated by [MetagenomeAnnotationActivity](https://microbiomedata.github.io/nmdc-schema/MetagenomeAnnotationActivity/)
- [ ] make data object record to store the *_contigs.fna file with a data_object_type of 'Assembly Contigs' as an output file generated by [MetagenomeAnnotationActivity](https://microbiomedata.github.io/nmdc-schema/MetagenomeAnnotationActivity/)

**Comment by ssarrafan** [comment]
@aclum @kaijli @mbthornton-lbl @scanon I'm going to move this to the next sprint but please remove it or let me know if it's not actively being worked on.

**Comment by aclum** [comment]
This is in review, it has been testing in mongo dev and we are waiting for for new prod records. Duplicates #199

**Comment by aclum** [comment]
We now have ~150 annotations in mongo prod that use v1.1.0. However, as far as I can tell the code still has not been merged into the main branch ( https://github.com/microbiomedata/nmdc_automation/blob/main/configs/workflows.yaml still references v1.0.4)
