### ISSUE TITLE
Implement MetaTranscriptomics Workflow

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#195]
blockers are resolved on runtime dev, expected release to prod 7/29
blocked on https://github.com/microbiomedata/nmdc-schema/issues/1000
blocked on https://github.com/microbiomedata/nmdc-schema/issues/708

**Comment by ssarrafan** [comment]
@mbthornton-lbl This looks like a large task. Can it be broken down into smaller tasks that can be completed in 2 weeks?

**Comment by aclum** [comment]
This should be blocked on schema updates, we don't currently have all the output file types so this can't be completed yet.

**Comment by aclum** [comment]
Dependent tasks are expected to be resolved this week. Earliest this would be able to be tested in dev would be the week of July 22 which is when runtime dev would have the schema updates.

**Comment by aclum** [comment]
discussed this w/Shane this afternoon. First task would be to make a workflows-mt.yaml (name TBD). Next task would be update code to look back at the OmicsProcessing record to determine if `omics_type.has_raw_value` is `Metagenome` or `Metatranscriptome`

**Comment by aclum** [comment]
@mbthornton-lbl  we need to implement this outside of berkeley, then make sure it gets updated for berkeley.

**Comment by ssarrafan** [comment]
What's the status of this?  Is this being done this sprint? @aclum @mbthornton-lbl

**Comment by aclum** [comment]
This PR is still in review and needs input from Shane https://github.com/microbiomedata/nmdc_automation/pull/223 once that is done the scheduler logic needs to be updated and tested.

**Comment by ssarrafan** [comment]
#223 and both blockers listed above are all closed. Can this issue be completed and closed today?  @aclum @mbthornton-lbl

**Comment by ssarrafan** [comment]
@mbthornton-lbl any update on this issue?
