### ISSUE TITLE
ReadsQC shortReadsqc update (v1.0.10)

### ISSUE THREAD

**Issue by vlilanl** [microbiomedata/nmdc_automation#196]
Validation and runtime memory were increased in [shortReadsqc.wdl](https://github.com/microbiomedata/ReadsQC/blob/master/shortReadsqc.wdl).

- [ ] bump version in workflow.yaml to v1.0.10

**Comment by aclum** [comment]
We need this before we start re-running NEON data so target is the sprint starting July 1.

**Comment by aclum** [comment]
Stale, bumping directly to v1.0.12
