### ISSUE TITLE
Command to fix mal-formed data paths and update data files

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#198]
Depends on the output from the `find-affected-workflows` in
#186 

Implement a `process-affected-files` command to 
- Fix malformed workflow directories and add symbolic links from the old directory name
- Fix malformed workflow data file names and add symbolic links
- Write out JSON files with updates to be applied to the database via `queries:run` endpoint

Run on prod and apply updates to DB
- [x] Run process command on production filesystem to update dirs and filenames and get update JSON output files
- [x] Apply the resulting updates to the database via the `queries:run` endpoint

**Comment by mbthornton-lbl** [comment]
Blocked by: https://github.com/microbiomedata/nmdc-runtime/issues/575

**Comment by aclum** [comment]
This is not resolved, we still have 180 assemblies where the paths don't resolve. This is different than the blade issues for EMP500.

**Comment by mbthornton-lbl** [comment]
This issue will can be closed after closing
- [ ] #214

**Comment by mbthornton-lbl** [comment]
159 of 179 data sets processed as of this morning.

**Comment by mbthornton-lbl** [comment]
{
  "ok": 1,
  "n": 900,
  "nModified": 900,
  "upserted": null,
  "writeErrors": null
}
