### ISSUE TITLE
Update workflows to latest versions

### ISSUE THREAD

**Issue by scanon** [microbiomedata/nmdc_automation#199]
Per @aclum

MAGs should use version v1.3.3
Annotation should use version v1.1.0

Also add the assembly file from *_contigs.fna file with a data_object_type of 'Assembly Contigs' as an output file generated by [MetagenomeAnnotationActivity](https://microbiomedata.github.io/nmdc-schema/MetagenomeAnnotationActivity/)

**Comment by scanon** [comment]
Per @aclum 

MAGs should use version v1.3.1
Annotation should use version v1.1.0

Also add the assembly file from *_contigs.fna file with a data_object_type of 'Assembly Contigs' as an output file generated by [MetagenomeAnnotationActivity](https://microbiomedata.github.io/nmdc-schema/MetagenomeAnnotationActivity/)

**Comment by scanon** [comment]
Test with `nmdc:omprc-13-nssdcy07`

**Comment by aclum** [comment]
MAG version [v1.3.3](https://github.com/microbiomedata/metaMAGs/tree/v1.3.3) has the fixes Shane wanted for the low quality bins.

overlapping with https://github.com/microbiomedata/nmdc_automation/issues/191

**Comment by ssarrafan** [comment]
@scanon @aclum what's the status of this?

**Comment by aclum** [comment]
MAGs is blocked on https://github.com/microbiomedata/metaMAGs/issues/37
for annotation version v1.1.0 we have results in mongo dev, Shane was planning on updating the prod image but I don't see any results from v1.1.0 in yet.

**Comment by aclum** [comment]
Duplicates https://github.com/microbiomedata/nmdc_automation/issues/107 and https://github.com/microbiomedata/nmdc_automation/issues/191 but leaving all 3 open since each has different information.

**Comment by ssarrafan** [comment]
> Duplicates [#107](https://github.com/microbiomedata/nmdc_automation/issues/107) and [#191](https://github.com/microbiomedata/nmdc_automation/issues/191) but leaving all 3 open since each has different information.

So are all 3 active?

**Comment by aclum** [comment]
https://github.com/microbiomedata/nmdc_automation/issues/191 is resolved.

**Comment by aclum** [comment]
Closing this as related tickets are resolved.
