### ISSUE TITLE
NEON JGI data did not transfer over raw and filtered fastq files

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#20]
There is a bug in the JGI ingest code which resulted in the raw and filtered data not being staged correctly.
This blocks https://github.com/microbiomedata/issues/issues/264

**Comment by aclum** [comment]
@mflynn-lanl Did these fixes get merged in?

**Comment by ssarrafan** [comment]
Moving to next sprint per @mflynn-lanl

**Comment by aclum** [comment]
I believe this is resolved, @Michal-Babins  has ingested the JGI workflow data.
