### ISSUE TITLE
ReadbasedAnalysis Version 1.0 (v1.0.7)

### ISSUE THREAD

**Issue by vlilanl** [microbiomedata/nmdc_automation#202]
Workflows were updated to Version 1.0
- [ ] bump version in workflow.yaml to 1.0.7

**Comment by aclum** [comment]
@scanon this is lower priority than getting annotation and binning updated but includes database updates for gottcha2 to include fungal so would be good to add. It also uses WDL 1.0.

**Comment by aclum** [comment]
this is on 1.0.8 now
