### ISSUE TITLE
make sure we have a complete and single mapping file for napa re-iding for all 8 studies

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#203]
See PR comments 
https://github.com/microbiomedata/nmdc_automation/pull/187

several studies don't have have workflow activity mappings in their *_updated_record_identifiers.tsv files

studies missing workflow activity records:
 - [x] nmdc:sty-11-547rwq94
 - [x] nmdc:sty-11-076c9980
 - [x] nmdc:sty-11-1t150432
 - [x] nmdc:sty-11-dcqce727

https://github.com/microbiomedata/nmdc_automation/commit/0ba0d4f66f3a52e9fdff63c339d1e1df08771e43 was the commit that deleted the workflow activities for nmdc:sty-11-547rwq94 so that would be a good place to start to see how to fix the other 3 studies

studies with multiple *_updated_record_identifiers*.tsv files, 
 -  [x] nmdc:sty-11-33fbta56
 -  [x] nmdc:sty-11-aygzgv51
i believe _updated_record_identifiers_l.tsv is the more complete record to be retained. If you agree, please delete the less complete record

**Comment by mbthornton-lbl** [comment]
Addressed by these commits:

nmdc:sty-11-076c9980:
https://github.com/microbiomedata/nmdc_automation/pull/187/commits/477a3ec60f620dc36c75f05b4ff4af4f290bcf28
nmdc:sty-11-1t150432:
https://github.com/microbiomedata/nmdc_automation/pull/187/commits/dda9e096269b5eee1f717febadcc65c669b54be5
nmdc:sty-11-dcqce727:
https://github.com/microbiomedata/nmdc_automation/pull/187/commits/8deda3102358dd0ec5414234168ddb312e763272

**Comment by mbthornton-lbl** [comment]
Cases with multiple `updated_identifiers` files were resolved by merging the two files

https://github.com/microbiomedata/nmdc_automation/pull/187/commits/545f73b4219b2f87bbb9e013ade9f3d16287de75

https://github.com/microbiomedata/nmdc_automation/pull/187/commits/c89525dc279391779f325675eaf2bd80649482b9
