### ISSUE TITLE
Fix dependency logic

### ISSUE THREAD

**Issue by scanon** [microbiomedata/nmdc_automation#211]
The scheduler doesn't properly deal with cases where there the most recent activity version is still in range but still triggers a downstream version.

For example, assume there is an assembly run that is 1.02 and 1.03 is the current version.  This should be fine and should be used to trigger an annotation run.  This doesn't seem to be the case.

**Comment by aclum** [comment]
@scanon  can this be closed? There is a merged linked PR.
