### ISSUE TITLE
Create test instance of each workflow that leaverage Berkeley schema & new runtime

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#220]
Covers:
<google-sheets-html-origin>
G1 | All: Create test instance of each workflow that leaverage Berkeley schema & new runtime
-- | --

Create updated Workflows for:
- [ ] Sequencing Noninterleaved
- [ ] Sequencing Interleaved
- [ ] Reads QC
- [ ] Reads QC Interleave
- [ ] Metagenome Assembly
- [ ] Metagenome Annotation
- [ ] MAGs
- [ ] Readbased Analysis

For each of the above Workflows:
- [ ] Create workflow unit tests
- [ ] Implement basic CI to run unit tests

**Comment by ssarrafan** [comment]
removing from sprint, last day of sprint, already has backlog label on it

**Comment by aclum** [comment]
Sequencing Interleaved & Sequencing Noninterleaved are not part of MVP and need to be deprecated eventually.

**Comment by mslarae13** [comment]
@mbthornton-lbl can we remove this from this squad board?
It sounds like this task is being worked on but I'd like to close out the project board.

Is this being tracked elsewhere? Or just not currently being worked on?
@aclum

**Comment by aclum** [comment]
Doesn't appear to be active.

**Comment by mslarae13** [comment]
@mbthornton-lbl is this still useful? Can we close this out as not planned? Assuming the work is being tracked elsewhere?

**Comment by mbthornton-lbl** [comment]
No longer relevant / closing as no-op
