### ISSUE TITLE
Update workflow automation to use Berkley-style API endpoints

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#221]
Covers:
<google-sheets-html-origin><style type="text/css"></style>
G5 | All: Update workflow automation to use Berkley API endpoints
-- | --

- [x] Update workflow automation API interactions to use the Berkley-style Runtime endpoints
- [x] Add / improve automated testing for API interactions

**Comment by aclum** [comment]
blocked on https://github.com/microbiomedata/nmdc-runtime/issues/593
