### ISSUE TITLE
update import logic to update OmicsProcessing record

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#239]
The import automation should make a DataObject record and add is to has_output on the NucelotideSequencing record. The NucelotideSequencing record will be part of the import csv file. I believe nmdc_automation/import_automation/activity_mapper.py is where this needs to be updated. It needs to do this instead of the current behavior which is to make a ReadQc record without an input data object.

We talked about doing this with a queries:run command since the NucelotideSequencing record will already exist.

When updating for this issue, also address:
- #267 
- #259

**Comment by ssarrafan** [comment]
@mbthornton-lbl @scanon @aclum can this one be closed this sprint?

**Comment by aclum** [comment]
Work has not started on this, moving to the next sprint. This will be worked on once https://github.com/microbiomedata/nmdc_automation/issues/251 is done.

**Comment by ssarrafan** [comment]
251 is closed. PR being reviewed now.  Hopefully it can be closed by Friday?
