### ISSUE TITLE
ReadsQC - updated logic to take in more than one file (v1.0.11)

### ISSUE THREAD

**Issue by vlilanl** [microbiomedata/nmdc_automation#241]
[ShortreadsQC](https://github.com/microbiomedata/ReadsQC/blob/master/shortReadsqc.wdl) is now able to take multiple interleaved or non-interleaved files.

- [ ] bump version in workflow.yaml to 1.0.11
- [ ] format of [input.json](https://github.com/microbiomedata/ReadsQC/blob/master/input.json) needs to be updated to accommodate changes introduced in v1.0.11
- [`input_fq1`](https://github.com/microbiomedata/ReadsQC/blob/d0915ae84a9f246f44fbed891fc362811728af0d/input.json#L3) and [`input_fq2`](https://github.com/microbiomedata/ReadsQC/blob/d0915ae84a9f246f44fbed891fc362811728af0d/input.json#L6) take in reads 1 and 2 of non-interleaved files
- [`input_files`](https://github.com/microbiomedata/ReadsQC/blob/d0915ae84a9f246f44fbed891fc362811728af0d/input.json#L2) takes in interleaved files.

**Comment by aclum** [comment]
Note: order needs to be the same for input_fq1 and input_fq2.

**Comment by mslarae13** [comment]
not MVP for berkeley-schema roll out

**Comment by aclum** [comment]
This should not be cancelled, the wdl changes have been made already so we need to make these updates in order to progress to newer versions.

**Comment by ssarrafan** [comment]
@aclum can this be completed this sprint?
