### ISSUE TITLE
Update `nmdc_automation.import_automation` to be compatible with Berkley metadata and endpoints

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#254]
- Update `GoldMapper` class to map to `nmdc.WorkflowExecution` metadata classes
- Update tests and fixtures to be Berkley compatible
- Refactor to use prod .yaml configuration files for testiing

**Comment by aclum** [comment]
Suggest leaving task 'Refactor to use prod .yaml configuration files for testing' aside for now until we figure out how to deal with test coverage vs default production config.

**Comment by ssarrafan** [comment]
@aclum @mbthornton-lbl are you expecting this to be reviewed/closed by Friday this week?  Does this need to be moved to the next sprint?

**Comment by aclum** [comment]
Shreyas reviewed this but Michael still hasn't gotten a chance to so moving this to the next sprint.

**Comment by aclum** [comment]
This was merged in today.
