### ISSUE TITLE
ReadsQC Output Update (v1.0.12)

### ISSUE THREAD

**Issue by vlilanl** [microbiomedata/nmdc_automation#255]
Included filter_stat_json into output for shortreads because NMDC-EDGE needs it:
https://github.com/microbiomedata/ReadsQC/blob/ddc0cd9f79cc53aa9cf25b40cf67196b5cd71a29/shortReadsqc.wdl#L68

- [ ] bump version in workflow.yaml to 1.0.12

**Comment by aclum** [comment]
see changes needed for 1.0.11  #241

**Comment by ssarrafan** [comment]
@aclum are you expecting this to be done by Friday?  Does it need to be bumped to the next sprint?
