### ISSUE TITLE
Configure and Deploy Berkley RC1 

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#256]
- [x] Set up deployment location on perlmutter: `/global/cfs/cdirs/m3408/nmdc_automation`
- [x] Configure environment variable and create a  `berkley_confg.toml`  to point to Berkley API and MongoDB
- [ ] Spin up a `Scheduler` for testing
- [ ] Run Watcher and submit job for nmdc:omprc-11-cegmwy02
- [ ] Fix run_workflows.py as needed

**Comment by ssarrafan** [comment]
Can this be closed @mbthornton-lbl ?

**Comment by ssarrafan** [comment]
No updates but will move to next sprint since @mbthornton-lbl is out sick till next week
FYI @aclum
