### ISSUE TITLE
Create Dashboard to Track Workflow Processing 

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc_automation#27]
Build out dashboard that is able to adress the following:

- [ ] Build out FastApi to support wanted queries 
- [ ] Build out React Front end and components 
- [ ] Have dashboard that allows users to query by omics id, cromwell id, or study id

**Comment by ssarrafan** [comment]
JAWS has dashboard. Use that if possible.  
Closing this issue per @shreddd
