### ISSUE TITLE
Watcher.watch not handling state file correctly

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#275]
Trial run of the `daemon` command appears to have resulted in an empty agent.state file in 
/global/cfs/cdirs/m3408/var/dev

Test state file was a copy of
/global/cfs/cdirs/m3408/var/prod/agent.state

**Comment by ssarrafan** [comment]
@scanon can you please review #278 so we can close this one.

**Comment by aclum** [comment]
PR was merged into main today.
