### ISSUE TITLE
get_token errors when testing on dev

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#280]
Im trying to test https://github.com/microbiomedata/issues/issues/819 and there are errors with get_token when using dev. I am able to get a token from runtime dev with swagger UI using the client credentials for nmdcda.

to reproduce:
(nmdc_automation) nmdcda@perlmutter:login33:/global/cfs/cdirs/m3408/users/nmdcda/repos/nmdc_automation> poetry run python nmdc_automation/run_process/run_import.py import-projects test_import.csv configs/import.yaml configs/site_configuration.toml

where api_url = "https://api-dev.microbimedata.org"

and 
cat test_import.csv
nucleotide_sequencing_id	project_id	project_path
nmdc:omprc-11-ycnhgw23	Ga0597026	/global/cfs/projectdirs/m3408/aim2/dev/bioscales_mapping/neon_analysis_projects/Ga0597026/

**Comment by ssarrafan** [comment]
There is a thread on Slack about this.  @mbthornton-lbl @aclum @shreddd assuming this will continue for the next sprint.
