### ISSUE TITLE
Refactor `jgi_file_staging` unit tests

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#30]
Acceptance Criteria:
- all unit tests moved from `jgi_file_staging/tests` to top level `tests` directory
- Fix import errors and make unit tests run

**Comment by ssarrafan** [comment]
Appears to be in progress?  Moving to next sprint. @mbthornton-lbl let me know if this should be in the backlog.

**Comment by mbthornton-lbl** [comment]
Addressed along with CI automation in PR 
#34
