### ISSUE TITLE
implement automated unit test worflow on `main` and branches via github actions

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#31]
Acceptance criteria:
- Implement workflow to automatically run unit tests
- run coverage and generate html report

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint, adding backlog label. Please update or add to next sprint if still active.

**Comment by mbthornton-lbl** [comment]
PR #34 was approved and merged last week
