### ISSUE TITLE
Re-id logic for metatranscriptomes

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#40]
For re-iding we are just re-iding and not reprocessing metatranscriptomes.
legacy study ids gold:Gs0135149 or gold:Gs0110138 can be used to test this.
Testing should be done against the napa mongo instance.

**Comment by aclum** [comment]
We reviewed this today and logic updates are needed to handle records which don't have data_object_type or url populated and use a directory convention that predates using GOLD project IDs, instead using jgi proposal id_ img submission id??

**Comment by ssarrafan** [comment]
> We reviewed this today and logic updates are needed to handle records which don't have data_object_type or url populated and use a directory convention that predates using GOLD project IDs, instead using jgi proposal id_ img submission id??

I'll re-open this. Should this go in the backlog or next sprint?
