### ISSUE TITLE
Add Jaws API Support to nmdc_automation

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc_automation#42]
Nmdc Automation is prepped to support JAWS integration. We need to be able to utilize the JAWS api to run our worklfows end-end. 

Here is what we need:
[x]Add wrapper around JAWs API
[]Test Jaws API with our workflows on perlmutter

**Comment by ssarrafan** [comment]
@scanon @Michal-Babins are you working on this this week?

**Comment by Michal-Babins** [comment]
Yes, we will start looking into this this week.

**Comment by ssarrafan** [comment]
Appears to be active.  Will move to the next sprint and also add to the new [JAWS Squad board](https://github.com/orgs/microbiomedata/projects/118/views/1).

**Comment by Michal-Babins** [comment]
Starting this week.

**Comment by Michal-Babins** [comment]
This part is done,  I will make a new ticket for the next steps.
