### ISSUE TITLE
Null values being submitted by a Re-ID-ing tool

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#44]
Might be a long shot, but could anyone shine any light on this record in the data_object_set on prod?
{
    "_id": {"$oid": "65affcdc07a1abea27b3fa0a"},
    "alternative_identifiers": [],
    "compression_type": null,
    "data_object_type": "Metagenome Raw Reads",
    "description": "Raw sequencer read data",
    "file_size_bytes": 2861414297,
    "id": "nmdc:dobj-11-77e9jm46",
    "md5_checksum": null,
    "name": "9422.8.132674.GTTTCG.fastq.gz",
    "type": "nmdc:DataObject",
    "was_generated_by": null
}
Like, any guesses about where it came from?
My interest in it is that it used to have a url field explicitly set to null (as opposed to simply being unset). That caused the post-release ingest to fail yesterday. So I manually intervened and $unset the url field on that record, which allowed the ingest to complete successfully. There are certainly plenty of data_object_set objects where the url is unset (db.data_object_set.find({ "url": { $exists: false } })) so I guess I’m just curious why that was was the way it was. At the end of the day the ingest code should probably be robust enough to handle the explicit null, but I figured I throw it out there in case anyone wanted to look at where it came from in the first place.

**Comment by mbthornton-lbl** [comment]
I have looked through the Re-ID-ing code, and the data files that it produces:

- Nulls, empty arrays, empty strings are not being introduced by `process-records` 
- `ingest-records` relies on the workflow endpoint `v1/workflows/activities` which relies on the schema `Database` and related model classes. This does not allow non-compliant values / Nulls etc.

**Comment by mbthornton-lbl** [comment]
@aclum @pkalita-lbl @Michal-Babins I don't think any of the Re-ID-ing tools are introducing Null values / empty arrays etc.  If you concur we can close this issue

**Comment by aclum** [comment]
agree let's close this.
