### ISSUE TITLE
Create tool to restore deleted Stegen study Workflows and Data Objects

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#47]
We need a tool to 
- Check if the objects exist
- Insert records

**Comment by Michal-Babins** [comment]
This should be done, we can review this in the morning

**Comment by ssarrafan** [comment]
Is this done?  @Michal-Babins I will close this based on your last comment but please add more details here. I'm trying to close out the last sprint.
