### ISSUE TITLE
Look over all werkflow branches for metaG workflow and begin merge into main

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc_automation#6]
We need to go and start merging the workflow automation styled workflow WDL's into the master branches and make updated released. 

Steps for approach should be:
1. Review WDL's and make sure they are up to standard
2. After review, merge to master 
3. Create releases
4. Look into github actions to automatically create releases

**Comment by ssarrafan** [comment]
@Michal-Babins is this actively being worked on?

**Comment by Michal-Babins** [comment]
Yes, this is.

**Comment by aclum** [comment]
We've copied over current database versions for binning and are testing a version of the binning docker that will be close to what will be run. There is a pull request in to update the file type enums.

**Comment by ssarrafan** [comment]
@Michal-Babins @aclum next sprint or backlog for this issue?

**Comment by Michal-Babins** [comment]
This has been completed.
