### ISSUE TITLE
Update `re_id_tool.py` to not rely on the changesheets:submit endpoint

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#64]
The changesheets being produced in `process-records` do not validate - reason being a conflict between the re-ID'ed data using the current rules for gold alternative identifiers - `gold:12345` while the Napa endpoint is still on schema version 7.8 where this convention is `Gold:123435`

Work around this by making the updates directly via PyMongo

**Comment by ssarrafan** [comment]
@mbthornton-lbl will this be done by tomorrow or did you mean to add this to the next sprint?

**Comment by mbthornton-lbl** [comment]
@ssarrafan it should at be ready for review by tomorrow.  It's a fairly small change, so maybe possible to get it reviewed and closed before the end end of the day tomorrow 🤞
