### ISSUE TITLE
Add logic for Napa-compliance updating of Study, BioSamples and OmicsProcessing to `re_id_tool.py` 

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#66]
Bring over the Re-ID-ing logic from @aclum 

https://github.com/microbiomedata/nmdc-schema/blob/napa_compliance/nmdc_schema

and incorporate it as `Click` command(s) in `re_id_tool.py`

New Study ID's have been created manually, so we want to make sure to use them

We will need:

- Update Study:  To Napa and schema version 10 standards
- Update BioSamples
- Update OmicsProcessing

**Comment by ssarrafan** [comment]
@mbthornton-lbl should this be in the next sprint or not?
