### ISSUE TITLE
Updates to file type enumerations for binning workflow

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#67]
We need to update the metadata json creation for the binning pipeline. New file types were added and one file type was changed. This needs to happen before we re-start running the binning pipeline.
See this[ PR](https://github.com/microbiomedata/nmdc-schema/pull/1791/files)
New file types:
Metagenome Bins Heatmap
Metagenome Bins Barplot
Metagenome Bins Krona Plot
Metagenome LQ Bins Compression File

Changed:
Metagenome HQMQ Bins Compression File

Depends on:
runtime dev being updated to schema version 10.2

This needs to be changed both for:
- [ ] JGI data ingest yaml (michael) -this one is less time sensitive.
- [x] NMDC workflow runs (shane)

**Comment by ssarrafan** [comment]
@scanon @mbthornton-lbl what's the status of this issue?

**Comment by aclum** [comment]
We are unblocked for what we need for GSP so not sure if you want to take it off that board @ssarrafan

**Comment by ssarrafan** [comment]
> We are unblocked for what we need for GSP so not sure if you want to take it off that board @ssarrafan

I'll remove it from the GSP board then.
