### ISSUE TITLE
Improve import code to be more dynamic and fail save

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc_automation#7]
Task:

Improve existing code for data import from JGI to NMDC. 

Needs:
Improve data object generation code
Improve API interaction code
Track state if data imports and data transforms via mongoDB 

Edge Cases:
Be able to handle 2 AP's under one sequencing project

**Comment by ssarrafan** [comment]
@Michal-Babins @mflynn-lanl @scanon what is the status of this ticket?  

I'll move to next sprint as it appears to be ready for review under the werkflow automation board

**Comment by Michal-Babins** [comment]
Can close it. The import code has been improved.
