### ISSUE TITLE
update workflow automation mg_annotation version to v1.0.5

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc_automation#78]
This version contains the updated product lookup files which were address in https://github.com/microbiomedata/mg_annotation/issues/25.

This needs to be updated before we start processing full workflows again.

**Comment by ssarrafan** [comment]
@aclum is this required for GSP?  
FYI @scanon

**Comment by ssarrafan** [comment]
@scanon any update on this issue?

**Comment by ssarrafan** [comment]
moving to next sprint per @vlilanl 
@kaijli and @scanon let me know if you won't be working on this issue

**Comment by aclum** [comment]
This was completed last sprint. There are several hundred annotation records in mongo prod tagged with version v1.0.5.
