### ISSUE TITLE
Package up automation code into distributable and maintainable code 

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/nmdc_automation#8]
Task:

We need to be able to streamline the automation process in a manageable and transparent way. This included taking current code base and making it more readable, intuitive, and fail safe. 

Improvements:
Track config via toml file
Make code more modular and maintainable
Create pypi/conda package for cross team usability

**Comment by ssarrafan** [comment]
Moving to new sprint as status was changed to in progress 2 days ago

**Comment by Michal-Babins** [comment]
This is still active. Some of this is dependent on how we treat Paired End vs Interleaved Metagenome Sequencing Reads from the omic processing record.

**Comment by ssarrafan** [comment]
@Michal-Babins any update on this? 

@hubin-keio @aclum

**Comment by Michal-Babins** [comment]
Depends on how we want to go about releasing version one. This has been ready and continuously updated for internal use, but could potentially be dependent on multiple things. We have a way forward dealing with Paired End vs Metagenome reads. However, since the submission end point for JAWs is not ready for us to use yet, there is no reason to release a version 1.0.0 when hopefully soon we can incorporate JAWs configuration out the box instead of releasing with only direct cromwell support and then in a few months dropping a version 2.0.0 since incorporating JAWs could be part of a Major release. Worth longer discussion within the workflows squad, but generally I would keep this as still active since what we need is there, but dependencies and structure might change.

**Comment by ssarrafan** [comment]
I'm removing this from the sprint. I don't see any updates in the last 2 weeks.  Let me know if you'd like to add it to a future sprint when you start working on it.  
@Michal-Babins @hubin-keio @scanon
