### ISSUE TITLE
Re-ID and verify studies in Test environment

### ISSUE THREAD

**Issue by mbthornton-lbl** [microbiomedata/nmdc_automation#89]
For each study below, perform the following steps in the testing environment:
- Perform Re-ID and data cleanup steps as necessary on Study
- Extract study and run `linkml-validate` for schema compliance

Update Studies and Validate vs Schema:
- [x] #90
- [ ] #91
- [x] #99
- [x] #102 
- [x] #103 
- [x] #109
- [x] #111
- [x] #105

After all studies are updates, Run `data_qc` queries against the entire DB:
- [ ] biosample_part_of_study.js
- [ ] data_object_was_generated_by_activity_or_omics_processing.js
- [ ] extraction_has_input_biosample_or_processed_sample.js
- [ ] functional_annotation_agg_metagenome_metatranscriptome_annotation_id.js
- [ ] metabolomics_analysis_acrtivity_has_calibration_data_object.js
- [ ] nom_analysis_activity_has_calibration_data_object.js
- [ ] omics_processing_has_input_biosample_or_processed_sample.js
- [ ] omics_processing_has_output_data_objects.js
- [ ] omics_processing_part_of_study.js
- [ ] orphan_data_objects.js
- [ ] pooling_has_input_biosample_or_processed_sample.js
- [ ] workflow_execution_has_input_data_objects.js
- [ ] workflow_execution_has_output_data_objects.js
- [ ] workflow_execution_part_of_omics_processing.js
- [ ] workflow_execution_part_of_omics_processing_or_workflow_execution.js
- [ ] workflow_execution_was_informed_by_omics_processing.js

Full DB validation:
- [ ] Extract and linkml-validate full DB
- [ ] Convert to triplestore
- [ ] Upload to GraphDB / Fuseki

Functional:
- [ ] Spin up Portal and point to Test DB

**Comment by aclum** [comment]
We are missing **delete-old-binning-data** to get rid of straggler legacy data objects which should come after Delete Orphan Workflows and Data Objects.

**Comment by ssarrafan** [comment]
@mbthornton-lbl will be continuing to work on this in the next sprint per Slack message. Moving over.

**Comment by aclum** [comment]
linkml validate completes on study_set, biosample_set and omics_processing_set has expected errors for has_output b/c only update-study has been run.
